### PR TITLE
Grammatical fix

### PR DESCRIPTION
**Pull request by SerMock**
Changed from "why"s to "why".

***Make sure to fill out everything below — your pull request won't be merged until you do!***

Check **all** applicable boxes below (put an **x** in between the square brackets, with no spaces)

- [x ] This is to fix an issue. **Issue**: #
- [x ] If I modified any **JS file, other than adding comments or whitespace**, I ran `npm run build` and `npm test`

## Summary
Explain your pull request
Grammatical fix

### CODE REVIEW

**Comment by nebrelbug** [comment]
@SerMock looks great! I'll try to merge this when I get home

**Comment by nebrelbug** [comment]
Congrats @SerMock for your first contribution! If it's alright, can I add you to the contributors on the README?

**Comment by SerMock** [comment]
Not a problem good sir, thanks!

**Comment by nebrelbug** [comment]
@all-contributors please add @SerMock for code

**Comment by nebrelbug** [comment]
@SerMock thanks for the pull request, you're now listed as a contributor on the README!

Hope you contribute more to Squirrelly in the future!

**Pull request merged**
