### PR TITLE
Update file handler renderFile function

### LINKED ISSUE #200: An error can occur if no data is passed to renderFile() as no check is done to see if data is defined
**Describe the bug**

When using renderFile if the data parameter is not passed it can cause an error as there is no check to see if it is undefined.

Changing [this](https://github.com/squirrellyjs/squirrelly/blob/master/dist/squirrelly.cjs.js#L1062-L1076) section of code to the following ensures no error will occur:
```js
    if (data != undefined){
        if (data.settings) {
            // Pull a few things from known locations
            if (data.settings.views) {
                Config.views = data.settings.views;
            }
            if (data.settings['view cache']) {
                Config.cache = true;
            }
            // Undocumented after Express 2, but still usable, esp. for
            // items that are unsafe to be passed along with data, like `root`
            var viewOpts = data.settings['view options'];
            if (viewOpts) {
                copyProps(Config, viewOpts);
            }
        }
    } 
``` 

**Environment:** Node

### PR DESCRIPTION
**Pull request by futurelucas4502**
Updated the file_handler renderFile function to allow for an undefined data parameter fixing a crash

* Fixes #200

### CODE REVIEW

**Comment by nebrelbug** [comment]
@futurelucas4502 this looks fantastic! I'll merge right now.

By the way, are you ok if I add you to the README as a contributor?

**Comment by futurelucas4502** [comment]
@nebrelbug yeah that'd be awesome! 😄

**Comment by nebrelbug** [comment]
@all-contributors please add @futurelucas4502 for bugs and code.

**Comment by nebrelbug** [comment]
@futurelucas4502 just added you to the README :tada: 

Thank you! Hope you're able to contribute in the future :smiley:

**Pull request merged**
